//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StarBusModel", "FK_SeatDetails_BookingDetails", "BookingDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StarBusModel.BookingDetail), "SeatDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarBusModel.SeatDetail), true)]

#endregion

namespace StarBusModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StarBusEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StarBusEntities1 object using the connection string found in the 'StarBusEntities1' section of the application configuration file.
        /// </summary>
        public StarBusEntities1() : base("name=StarBusEntities1", "StarBusEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StarBusEntities1 object.
        /// </summary>
        public StarBusEntities1(string connectionString) : base(connectionString, "StarBusEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StarBusEntities1 object.
        /// </summary>
        public StarBusEntities1(EntityConnection connection) : base(connection, "StarBusEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookingDetail> BookingDetails
        {
            get
            {
                if ((_BookingDetails == null))
                {
                    _BookingDetails = base.CreateObjectSet<BookingDetail>("BookingDetails");
                }
                return _BookingDetails;
            }
        }
        private ObjectSet<BookingDetail> _BookingDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeatDetail> SeatDetails
        {
            get
            {
                if ((_SeatDetails == null))
                {
                    _SeatDetails = base.CreateObjectSet<SeatDetail>("SeatDetails");
                }
                return _SeatDetails;
            }
        }
        private ObjectSet<SeatDetail> _SeatDetails;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookingDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookingDetails(BookingDetail bookingDetail)
        {
            base.AddObject("BookingDetails", bookingDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeatDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeatDetails(SeatDetail seatDetail)
        {
            base.AddObject("SeatDetails", seatDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StarBusModel", Name="BookingDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookingDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookingDetail object.
        /// </summary>
        /// <param name="bookingID">Initial value of the BookingID property.</param>
        public static BookingDetail CreateBookingDetail(global::System.Int32 bookingID)
        {
            BookingDetail bookingDetail = new BookingDetail();
            bookingDetail.BookingID = bookingID;
            return bookingDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookingID
        {
            get
            {
                return _BookingID;
            }
            set
            {
                if (_BookingID != value)
                {
                    OnBookingIDChanging(value);
                    ReportPropertyChanging("BookingID");
                    _BookingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookingID");
                    OnBookingIDChanged();
                }
            }
        }
        private global::System.Int32 _BookingID;
        partial void OnBookingIDChanging(global::System.Int32 value);
        partial void OnBookingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TourID
        {
            get
            {
                return _TourID;
            }
            set
            {
                OnTourIDChanging(value);
                ReportPropertyChanging("TourID");
                _TourID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TourID");
                OnTourIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TourID;
        partial void OnTourIDChanging(Nullable<global::System.Int32> value);
        partial void OnTourIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StarBusModel", "FK_SeatDetails_BookingDetails", "SeatDetails")]
        public EntityCollection<SeatDetail> SeatDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeatDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "SeatDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeatDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "SeatDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StarBusModel", Name="SeatDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeatDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeatDetail object.
        /// </summary>
        /// <param name="bookingID">Initial value of the BookingID property.</param>
        /// <param name="seatID">Initial value of the SeatID property.</param>
        public static SeatDetail CreateSeatDetail(global::System.Int32 bookingID, global::System.Int32 seatID)
        {
            SeatDetail seatDetail = new SeatDetail();
            seatDetail.BookingID = bookingID;
            seatDetail.SeatID = seatID;
            return seatDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookingID
        {
            get
            {
                return _BookingID;
            }
            set
            {
                if (_BookingID != value)
                {
                    OnBookingIDChanging(value);
                    ReportPropertyChanging("BookingID");
                    _BookingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookingID");
                    OnBookingIDChanged();
                }
            }
        }
        private global::System.Int32 _BookingID;
        partial void OnBookingIDChanging(global::System.Int32 value);
        partial void OnBookingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeatID
        {
            get
            {
                return _SeatID;
            }
            set
            {
                if (_SeatID != value)
                {
                    OnSeatIDChanging(value);
                    ReportPropertyChanging("SeatID");
                    _SeatID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SeatID");
                    OnSeatIDChanged();
                }
            }
        }
        private global::System.Int32 _SeatID;
        partial void OnSeatIDChanging(global::System.Int32 value);
        partial void OnSeatIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StarBusModel", "FK_SeatDetails_BookingDetails", "BookingDetails")]
        public BookingDetail BookingDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookingDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "BookingDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookingDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "BookingDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BookingDetail> BookingDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookingDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "BookingDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BookingDetail>("StarBusModel.FK_SeatDetails_BookingDetails", "BookingDetails", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
