/*
 * JS for EVENTS generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return '2edf0040-12df-4cb7-b475-63ca6b88e61c';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "EVENTS",
    "location": "EVENTS.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "aboutus",
    "location": "aboutus.html"
}];

EVENTS_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'events': 'EVENTS_events',
        'mobilenavbaritem_13': 'EVENTS_mobilenavbaritem_13',
        'mobilenavbaritem_14': 'EVENTS_mobilenavbaritem_14',
        'mobilenavbaritem_15': 'EVENTS_mobilenavbaritem_15',
        'mobilelist_17': 'EVENTS_mobilelist_17',
        'mobilelistitem_18': 'EVENTS_mobilelistitem_18',
        'mobilelistitembutton_19': 'EVENTS_mobilelistitembutton_19',
        'mobilelistitem_20': 'EVENTS_mobilelistitem_20',
        'mobilelistitembutton_21': 'EVENTS_mobilelistitembutton_21',
        'mobilelistitem_22': 'EVENTS_mobilelistitem_22',
        'mobilelistitembutton_23': 'EVENTS_mobilelistitembutton_23'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'EVENTS';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var EVENTS_beforeshow = function() {
            Appery.CurrentScreen = "EVENTS";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var EVENTS_onLoad = function() {
            EVENTS_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            EVENTS_deviceEvents();
            EVENTS_windowEvents();
            EVENTS_elementsEvents();
        };

    // screen window events
    var EVENTS_windowEvents = function() {

            $('#EVENTS').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var EVENTS_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var EVENTS_elementsExtraJS = function() {
            // screen (EVENTS) extra code

            /* mobilelist_17 */

            listView = $("#EVENTS_mobilelist_17");
            theme = listView.attr("data-theme");
            if (typeof theme !== 'undefined') {
                var themeClass = "ui-btn-up-" + theme;
                listItem = $("#EVENTS_mobilelist_17 .ui-li-static");
                $.each(listItem, function(index, value) {
                    $(this).addClass(themeClass);
                });
            }

            /* mobilelistitem_18 */

            /* mobilelistitem_20 */

            /* mobilelistitem_22 */

        };

    // screen elements handler
    var EVENTS_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#EVENTS_mobileheader [name="mobilenavbaritem_13"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('startScreen', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#EVENTS_mobileheader [name="mobilenavbaritem_13"]');

            $(document).off("click", '#EVENTS_mobileheader [name="mobilenavbaritem_15"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('aboutus', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#EVENTS_mobileheader [name="mobilenavbaritem_15"]');

        };

    $(document).off("pagebeforeshow", "#EVENTS").on("pagebeforeshow", "#EVENTS", function(event, ui) {
        EVENTS_beforeshow();
    });

    if (runBeforeShow) {
        EVENTS_beforeshow();
    } else {
        EVENTS_onLoad();
    }
};

$(document).off("pagecreate", "#EVENTS").on("pagecreate", "#EVENTS", function(event, ui) {
    Appery.processSelectMenu($(this));
    EVENTS_js();
});