/*
 * JS for IEEEORN generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return 'a6f92a65-75a5-4c86-9c70-8b0b027f9bed';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "IEEEORN",
    "location": "IEEEORN.html"
}, {
    "name": "parade",
    "location": "parade.html"
}, {
    "name": "phoenix2k13",
    "location": "phoenix2k13.html"
}];

IEEEORN_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_1': 'IEEEORN_mobilenavbar_1',
        'mobilenavbaritem_2': 'IEEEORN_mobilenavbaritem_2',
        'mobilenavbaritem_3': 'IEEEORN_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'IEEEORN_mobilenavbaritem_4',
        'mobileimage_7': 'IEEEORN_mobileimage_7',
        'html_8': 'IEEEORN_html_8',
        'mobileimage_9': 'IEEEORN_mobileimage_9',
        'html_10': 'IEEEORN_html_10'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'IEEEORN';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var IEEEORN_beforeshow = function() {
            Appery.CurrentScreen = "IEEEORN";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var IEEEORN_onLoad = function() {
            IEEEORN_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            IEEEORN_deviceEvents();
            IEEEORN_windowEvents();
            IEEEORN_elementsEvents();
        };

    // screen window events
    var IEEEORN_windowEvents = function() {

            $('#IEEEORN').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var IEEEORN_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var IEEEORN_elementsExtraJS = function() {
            // screen (IEEEORN) extra code

        };

    // screen elements handler
    var IEEEORN_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#IEEEORN").on("pagebeforeshow", "#IEEEORN", function(event, ui) {
        IEEEORN_beforeshow();
    });

    if (runBeforeShow) {
        IEEEORN_beforeshow();
    } else {
        IEEEORN_onLoad();
    }
};

$(document).off("pagecreate", "#IEEEORN").on("pagecreate", "#IEEEORN", function(event, ui) {
    Appery.processSelectMenu($(this));
    IEEEORN_js();
});