/*
 * JS for parade generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return 'a6f92a65-75a5-4c86-9c70-8b0b027f9bed';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "IEEEORN",
    "location": "IEEEORN.html"
}, {
    "name": "parade",
    "location": "parade.html"
}, {
    "name": "phoenix2k13",
    "location": "phoenix2k13.html"
}];

parade_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_1': 'parade_mobilenavbar_1',
        'mobilenavbaritem_2': 'parade_mobilenavbaritem_2',
        'mobilenavbaritem_3': 'parade_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'parade_mobilenavbaritem_4',
        'mobileimage_7': 'parade_mobileimage_7',
        'html_6': 'parade_html_6',
        'mobileimage_8': 'parade_mobileimage_8',
        'html_9': 'parade_html_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'parade';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var parade_beforeshow = function() {
            Appery.CurrentScreen = "parade";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var parade_onLoad = function() {
            parade_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            parade_deviceEvents();
            parade_windowEvents();
            parade_elementsEvents();
        };

    // screen window events
    var parade_windowEvents = function() {

            $('#parade').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var parade_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var parade_elementsExtraJS = function() {
            // screen (parade) extra code

        };

    // screen elements handler
    var parade_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#parade").on("pagebeforeshow", "#parade", function(event, ui) {
        parade_beforeshow();
    });

    if (runBeforeShow) {
        parade_beforeshow();
    } else {
        parade_onLoad();
    }
};

$(document).off("pagecreate", "#parade").on("pagecreate", "#parade", function(event, ui) {
    Appery.processSelectMenu($(this));
    parade_js();
});