/*
 * JS for phoenix2k13 generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return 'a6f92a65-75a5-4c86-9c70-8b0b027f9bed';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "IEEEORN",
    "location": "IEEEORN.html"
}, {
    "name": "parade",
    "location": "parade.html"
}, {
    "name": "phoenix2k13",
    "location": "phoenix2k13.html"
}];

phoenix2k13_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_2': 'phoenix2k13_mobilenavbar_2',
        'mobilenavbaritem_3': 'phoenix2k13_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'phoenix2k13_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'phoenix2k13_mobilenavbaritem_5',
        'mobileimage_15': 'phoenix2k13_mobileimage_15',
        'html_26': 'phoenix2k13_html_26',
        'mobileimage_27': 'phoenix2k13_mobileimage_27',
        'html_28': 'phoenix2k13_html_28'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'phoenix2k13';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var phoenix2k13_beforeshow = function() {
            Appery.CurrentScreen = "phoenix2k13";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var phoenix2k13_onLoad = function() {
            phoenix2k13_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            phoenix2k13_deviceEvents();
            phoenix2k13_windowEvents();
            phoenix2k13_elementsEvents();
        };

    // screen window events
    var phoenix2k13_windowEvents = function() {

            $('#phoenix2k13').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var phoenix2k13_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var phoenix2k13_elementsExtraJS = function() {
            // screen (phoenix2k13) extra code

        };

    // screen elements handler
    var phoenix2k13_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_3"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('IEEEORN', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_3"]');
            $(document).off("click", '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('IEEEORN', {
                            reverse: false
                        });

                    }
                },
            }, '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_4"]');
            $(document).off("click", '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_5"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('parade', {
                            reverse: false
                        });

                    }
                },
            }, '#phoenix2k13_mobileheader1 [name="mobilenavbaritem_5"]');

        };

    $(document).off("pagebeforeshow", "#phoenix2k13").on("pagebeforeshow", "#phoenix2k13", function(event, ui) {
        phoenix2k13_beforeshow();
    });

    if (runBeforeShow) {
        phoenix2k13_beforeshow();
    } else {
        phoenix2k13_onLoad();
    }
};

$(document).off("pagecreate", "#phoenix2k13").on("pagecreate", "#phoenix2k13", function(event, ui) {
    Appery.processSelectMenu($(this));
    phoenix2k13_js();
});