/*
 * JS for startScreen generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return '2edf0040-12df-4cb7-b475-63ca6b88e61c';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "EVENTS",
    "location": "EVENTS.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "aboutus",
    "location": "aboutus.html"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_2': 'startScreen_mobilenavbar_2',
        'mobilenavbaritem_3': 'startScreen_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'startScreen_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'startScreen_mobilenavbaritem_5',
        'mobileimage_6': 'startScreen_mobileimage_6',
        'html_9': 'startScreen_html_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_beforeshow = function() {
            Appery.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobileheader1 [name="mobilenavbaritem_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('EVENTS', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobileheader1 [name="mobilenavbaritem_4"]');
            $(document).off("click", '#startScreen_mobileheader1 [name="mobilenavbaritem_5"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('aboutus', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobileheader1 [name="mobilenavbaritem_5"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_js();
});